# Generated by Django 2.2.12 on 2021-06-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210623_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Availiable', 'Availiable'), ('Out Of Stock', 'Out Of Stock')], default='Availiable', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoty',
            field=models.CharField(choices=[('Desktop Accessories', 'Desktop Accessories'), ('Desktop Components', 'Desktop Components'), ('Desktop Pc', 'Desktop Pc'), ('Laptop', 'Laptop'), ('Laptop Components', 'Laptop Components'), ('Mobile & SmartPhones', 'Mobile & SmartPhones'), ('Mobile Accessories', 'Mobile Accessories'), ('Others', 'Others')], default='Desktop Accessories', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Intel', 'Intel'), ('Evga', 'Evga'), ('Fantech', 'Fantech'), ('Xiaomi', 'Xiaomi'), ('Asus', 'Asus'), ('Microsoft', 'Microsoft'), ('Xpg', 'Xpg'), ('Red Dragon', 'Red Dragon'), ('Oppo or Vivo', 'Oppo or Vivo'), ('One Plus', 'One Plus'), ('Lenovo', 'Lenovo'), ('Amd', 'Amd'), ('Nvedia', 'Nvedia'), ('Hp', 'Hp'), ('Msi', 'Msi'), ('Dell', 'Dell'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
