# Generated by Django 2.2.12 on 2021-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210701_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsSold', models.CharField(max_length=50)),
                ('totalPrice', models.IntegerField()),
                ('customerName', models.CharField(max_length=50)),
                ('customerContact', models.CharField(max_length=100)),
                ('soldDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
