# Generated by Django 2.2.12 on 2021-05-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='addressLine2',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
