# Generated by Django 2.2.12 on 2021-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
