# Generated by Django 2.2.12 on 2021-05-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_addressline2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='addressLine2',
        ),
    ]
