# Generated by Django 2.2.12 on 2021-06-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210524_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(default='Order Placed', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(default='Esewa', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
