# Generated by Django 2.2.12 on 2021-06-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210619_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(default='Order Placed', max_length=50),
        ),
    ]
