# Generated by Django 2.2.12 on 2021-06-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Pending', 'Order Pending'), ('Order Delivered', 'Order Delivered')], default='Order Received', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(choices=[('notPaid', 'notPaid'), ('paidEsewa', 'paidEsewa'), ('paidOnDelivery', 'paidOnDelivery')], default='notPaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Orders'),
        ),
    ]
